name: Test Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build test framework
      run: docker compose build --no-cache test-framework
      
    - name: Start services
      run: docker compose -f docker-compose.ci.yml up -d
      
    - name: Wait for services
      run: |
        echo "Waiting for services to be ready..."
        # Wait for httpbin
        for i in {1..30}; do
          if curl -f http://localhost:8080/get > /dev/null 2>&1; then
            echo "httpbin is ready"
            break
          fi
          echo "Waiting for httpbin... attempt $i"
          sleep 2
        done
        
        # Wait for RabbitMQ
        for i in {1..30}; do
          if curl -f http://localhost:15672 > /dev/null 2>&1; then
            echo "RabbitMQ is ready"
            break
          fi
          echo "Waiting for RabbitMQ... attempt $i"
          sleep 2
        done
        
        # Show service status
        docker compose ps
      
    - name: Run ${{ matrix.test-type }} tests
      run: |
        mkdir -p ./artifacts/allure-results ./artifacts/allure-report ./artifacts/reports

        case "${{ matrix.test-type }}" in
          "mock")
            docker compose -f docker-compose.ci.yml run --rm \
              -v ${{ github.workspace }}/artifacts/allure-results:/app/allure-results \
              -v ${{ github.workspace }}/artifacts/reports:/app/reports \
              test-runner-mock
            ;;
          "external")
            docker compose -f docker-compose.ci.yml run --rm \
              -v ${{ github.workspace }}/artifacts/allure-results:/app/allure-results \
              -v ${{ github.workspace }}/artifacts/reports:/app/reports \
              test-runner-external
            ;;
          "unit")
            docker compose -f docker-compose.unit.yml run --rm \
              -v ${{ github.workspace }}/artifacts/allure-results:/app/allure-results \
              -v ${{ github.workspace }}/artifacts/reports:/app/reports \
              test-framework
            ;;
        esac

    - name: Generate Allure report
      run: |
        docker compose -f docker-compose.ci.yml run --rm \
          -v ${{ github.workspace }}/artifacts/allure-results:/app/allure-results \
          -v ${{ github.workspace }}/artifacts/allure-report:/app/allure-report \
          test-framework allure generate allure-results --clean -o allure-report

    - name: Upload ${{ matrix.test-type }} results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: ${{ matrix.test-type }}-test-results
        path: |
          artifacts/allure-results/
          artifacts/allure-report/
          artifacts/reports/
        retention-days: 7
