name: Test Framework

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build test framework
      run: docker compose build test-framework
      
    - name: Start services
      run: docker compose up -d
      
    - name: Wait for services
      run: |
        sleep 10
        curl -f http://localhost:8080/get || echo "httpbin not ready"
        curl -f http://localhost:15672 || echo "RabbitMQ not ready"
      
    - name: Run tests
      run: docker compose run --rm test-framework
      
    - name: Generate reports
      run: |
        docker compose run --rm test-framework allure generate allure-results --clean -o allure-report
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          allure-results/
          allure-report/
          reports/
        retention-days: 30
